### ISSUE TITLE
Organization, Project 이름 정하기

### ISSUE THREAD

**Issue by baleian** [Alizzwell/common#3]
@tusbea @maru536 @hehe717 @vanche
생각 나는데로 코멘트 부탁드립니다.

**Comment by hehe717** [comment]
organization - illusion(환상) apex(최정상) geeks(괴짜) bully(양아치) trinity (삼위일체)

**Comment by hehe717** [comment]
project - algoview

**Comment by hehe717** [comment]
organization - chummy(다정한) chum(친구) clone(복제)

**Comment by hehe717** [comment]
organization - yuntegrity(윤인성)

**Comment by vanche** [comment]
organization - KingOfIntegrity

**Comment by hehe717** [comment]
organization - nali-poli( 나원재가 만든 (잼이 든) 소라 모양의 푸딩 )

**Comment by baleian** [comment]
organization - popstone 
(민중: populace, stone: 돌(석) = 민석)

**Comment by hehe717** [comment]
organization - yunity

**Comment by baleian** [comment]
메일오나테스트

**Comment by baleian** [comment]
Organization
- popstone (민중: populace, stone: 돌(석) = 민석)
- showking (쇼킹과 비슷한 발음. 왕(인성왕 윤희원)을 보여달라)
- wekind (we are kind... 우리는 친절한 사람들이기 때문에..)

Project 
- embodia (embody (형태를 부여하다) + idea)
- showgo (show + algo)
- showging (show + debugging)
- estose ("에스토스" easy to see 의 줄임말.)
- cinnamon (시나몬. 별 의미는 없음 걍 발음이 좋아서 ㅎㅎ 로고 만들기도 좋아보이고..) (헉 근데 이미 리눅스 관련 오픈소스이름 시나몬있네...)
- PSpartner (Problem Solving Partner)

**Comment by baleian** [comment]
# 결정
- 팀명: Al izz well
- 프로젝트명: This-play
